# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    curl_request:
        class: AppBundle\Services\CurlRequest
        # arguments:
    cache:
        class: AppBundle\Services\Cache
        arguments: ['%database_host%', '%database_name%', '%database_user%', '%database_password%']
    crawler:
        class: AppBundle\Services\Crawler
    url_replacer:
        class: AppBundle\Services\UrlReplacer